DROP TABLE IF EXISTS OFFER;

CREATE TABLE OFFER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  description VARCHAR(250) NOT NULL,
  currency VARCHAR(250) DEFAULT '£',
  price INT DEFAULT 0,
  expiration_date VARCHAR(250) NOT NULL,
  canceled BOOLEAN DEFAULT FALSE
);